### ISSUE TITLE
CodeQL does not run code analysis on .NET6

### ISSUE THREAD

**Issue by GwynethLlewelyn** [GwynethLlewelyn/restbot#7]
We will have to wait for them to upgrade their C# extraction tool in order to get RESTbot to compile in their workflow under .NET6...

So, for now, this issue will be frozen until CodeQL signals that they've done an upgrade.

**Comment by GwynethLlewelyn** [comment]
Done! It works now:

Putting in `.github/workflows/dotnet.yml`:

```yaml
name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
```
